#ifndef RUNTIME_CONFIG_H
#define RUNTIME_CONFIG_H

extern int LOG_INTERVAL_MS_RUNTIME;
extern int MAX_FILE_SIZE_MB_RUNTIME;
extern bool ROTATE_HOURLY_RUNTIME;
extern int AUTO_DELETE_DAYS_RUNTIME;

#endif